name: Deploy with Secrets

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Inject Secrets
        run: |
          sed -i "s|YOUR_IMGBB_API_KEY|${{ secrets.IMGBB_API_KEY }}|g" index.js
          sed -i "s|YOUR_DISCORD_WEBHOOK_URL|${{ secrets.DISCORD_WEBHOOK }}|g" index.js
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
