name: Send Discord Notification on New Request

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace GitHub PAT
        run: sed -i "s|__GITHUB_PAT__|${{ secrets.GITHUB_TOKEN }}|g" index.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  discord-notification:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send Discord notification
        if: github.event_name == 'issues' && github.event.action == 'opened'
        run: |
          WEBHOOK="${{ secrets.DISCORD_WEBHOOK }}"
          EMBED_JSON=$(echo "${{ github.event.issue.body }}" | sed -n '/```json/,/```/p' | sed '1d;$d')

          curl -X POST -H "Content-Type: application/json" \
            -d "$(jq -n \
              --arg content "📬 ${GITHUB_ACTOR} submitted a request" \
              --argjson embed "$EMBED_JSON" \
              '{username: "Model Request Bot", embeds: [$embed], content: $content}')" \
            "$WEBHOOK"
