name: Success Notification

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Admin Panel Access Granted'
          to: ${{ secrets.NOTIFICATION_EMAIL }}
          from: 'GitHub Actions'
          body: 'Your token has been validated and you can now access the admin panel.'
