name: Success Notification
on:
  workflow_dispatch:
    inputs:
      secret_email:
        description: 'Email to notify (from secrets)'
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Admin Panel Access Granted'
          to: ${{ inputs.secret_email }}
          from: 'GitHub Actions'
          body: 'Your token has been validated and you can now access the admin panel.'
