name: Token Validation

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Token to validate'
        required: true
      expiry:
        description: 'Token expiry in ISO 8601 format (e.g., 3021-06-26T12:05:40Z)'
        required: true

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Decrypt expiry
        id: load_expiry
        env:
          EXPIRY_ENCRYPTION_KEY: ${{ secrets.EXPIRY_ENCRYPTION_KEY }}
        run: |
          EXPECTED_EXPIRY=$(openssl enc -aes-256-cbc -d -base64 -in .github/expiry.enc -pbkdf2 -pass pass:"$EXPIRY_ENCRYPTION_KEY")
          echo "expected_expiry=$EXPECTED_EXPIRY" >> $GITHUB_OUTPUT

      - name: Validate Token
        env:
          VALID_TOKEN: ${{ secrets.ADMIN_PANEL_TOKEN }}
          EXPECTED_EXPIRY: ${{ steps.load_expiry.outputs.expected_expiry }}
        run: |
          echo "Input token: ${{ inputs.token }}"
          echo "Input expiry: ${{ inputs.expiry }}"
          echo "Expected expiry: $EXPECTED_EXPIRY"

          if [ "${{ inputs.token }}" != "$VALID_TOKEN" ]; then
            echo "::error::Invalid token"
            exit 1
          fi

          if [ "${{ inputs.expiry }}" != "$EXPECTED_EXPIRY" ]; then
            echo "::error::Expiry does not match expected value"
            exit 1
          fi

          if ! echo "${{ inputs.expiry }}" | grep -qE '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z$'; then
            echo "::error::Invalid ISO 8601 format. Expected YYYY-MM-DDTHH:MM:SS(.sss)?Z"
            exit 1
          fi

          EXPIRY_UTC=$(date -u -d "${{ inputs.expiry }}" +%s 2>/dev/null)
          CURRENT_UTC=$(date -u +%s)

          if [ "$EXPIRY_UTC" -lt "$CURRENT_UTC" ]; then
            echo "::error::Token has expired"
            exit 1
          fi

          echo "Token is valid"
